DROP TABLE autor  cascade;
DROP TABLE bibliotecario cascade;
DROP TABLE categoriaespecial cascade;
DROP TABLE categoriageneral cascade;
DROP TABLE editorial cascade;
DROP TABLE estado cascade;
DROP TABLE tipodocumento cascade;
DROP TABLE usuario cascade;
DROP TABLE prestamo cascade;
DROP TABLE ubicacion cascade;
DROP TABLE libro cascade;
DROP TABLE detallelibro cascade ;
DROP TABLE detalleprestamo cascade;