--Biblioteca
--Script para creacion de tablas en la BD
--Por Gabriel,Bryan,Nelson y Leonardo
--Creado sábado,4 de marzo de 2018
--Universidad Centroamericana ISI
-- Tabla Ubicación

CREATE TABLE ubicacion (
    idubicacion   NUMBER(3)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_ubicacion PRIMARY KEY ( idubicacion ),
    Pais        VARCHAR2(10) NOT NULL,
	Ciudad		VARCHAR2(10),
	Nacionalidad VARCHAR2(15) NOT NULL
	
);

-- TABLA Bibliotecario

CREATE TABLE bibliotecario (
    idbibliotecario   NUMBER(3)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_bibliotecario PRIMARY KEY ( idbibliotecario ),
    nombre            VARCHAR2(20) NOT NULL,
    apellido          VARCHAR2(20) NOT NULL
);

-- Tabla Estado

CREATE TABLE estado (
    idestado   NUMBER(2)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_estado PRIMARY KEY ( idestado ),
    estado     VARCHAR2(20) NOT NULL
);

-- Tabla TipoDocumento

CREATE TABLE tipodocumento (
    idtipodocumento   NUMBER(2)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_tipodocumento PRIMARY KEY ( idtipodocumento ),
    nombre            VARCHAR2(30) NOT NULL
);

-- TABLA CategoriaGeneral

CREATE TABLE categoriageneral (
    codigogeneral   NUMBER(3) PRIMARY KEY,
    nombre          VARCHAR(50) NOT NULL
);

-- Tabla Usuario
CREATE TABLE usuario (
    idusuario        NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_usuario PRIMARY KEY ( idusuario ),
    nombre           VARCHAR2(20) NOT NULL,
    apellido         VARCHAR2(20) NOT NULL,
    identificacion   VARCHAR2(20) NOT NULL,
    sexo             VARCHAR2(10),
    nacionalidad     VARCHAR2(20)
	    CONSTRAINT fk_USUARIO_ubicacion
            REFERENCES ubicacion ( idubicacion )
);

-- TABLA Autor

CREATE TABLE autor (
    idautor           NUMBER(5)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_autor PRIMARY KEY ( idautor ),
    nombre            VARCHAR2(20) NOT NULL,
    apellido          VARCHAR2(20) NOT NULL,
    sexo              VARCHAR2(10),
    nacionalidad      VARCHAR2(15)
		CONSTRAINT fk_AUTOR_ubicacioN
            REFERENCES ubicacion ( idubicacion )
    fechanacimiento   DATE NULL
);

-- TABLA CategoriaEspecial

CREATE TABLE categoriaespecial (
    codigoespecial   NUMBER(3) PRIMARY KEY,
    nombre           VARCHAR2(50) NOT NULL,
    codigogeneral    NUMBER(3) NOT NULL
        CONSTRAINT fk_catespecial_catgeneral
            REFERENCES categoriageneral ( codigogeneral )
);

-- Tabla Editorial

CREATE TABLE editorial (
    ideditorial   NUMBER(3)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_editorial PRIMARY KEY ( ideditorial ),
    nombre        VARCHAR(30) NOT NULL,
    idubicacion   NUMBER(3) NOT NULL
        CONSTRAINT fk_editorial_ubicacion
            REFERENCES ubicacion ( idubicacion )
);

-- TABLA LIBRO

CREATE TABLE libro (
    idlibro            NUMBER(7)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    isbn               VARCHAR2(13),
    CONSTRAINT pk_libro PRIMARY KEY ( idlibro,isbn ),
    titulo             VARCHAR2(50) NOT NULL,
    fechapublicacion   DATE NOT NULL,
    edicion            VARCHAR2(10),
    descripcion        VARCHAR2(300),
    paginas            NUMBER(4),
    numejemplares      NUMBER(2) NOT NULL,
    idubicacion        NUMBER(3) NOT NULL
        CONSTRAINT fk_ubicacion_libro
            REFERENCES ubicacion ( idubicacion ),
    idestado           NUMBER(2) NOT NULL
        CONSTRAINT fk_estado_libro
            REFERENCES estado ( idestado ),
    idtipodocumento    NUMBER(3) NOT NULL
        CONSTRAINT fk_tipodocumento_libro
            REFERENCES tipodocumento ( idtipodocumento ),
    codigo             NUMBER(3) NOT NULL
        CONSTRAINT fk_codigogeneral_libro
            REFERENCES categoriageneral ( codigogeneral ),
    codigoespecial     NUMBER(3) NOT NULL
        CONSTRAINT fk_codigoespecial_libro
            REFERENCES categoriaespecial ( codigoespecial )
);

-- TABLA PRESTAMO

CREATE TABLE prestamo (
    idprestamo        NUMBER(6)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_prestamo PRIMARY KEY ( idprestamo ),
    fechaprestamo     DATE NOT NULL,
    fechadevolucion   DATE NOT NULL,
    cantidad          NUMBER(2) NOT NULL,
    estado            VARCHAR2(10) NOT NULL,
    idusuario         NUMBER(4) NOT NULL
        CONSTRAINT fk_usuario_prestamo
            REFERENCES usuario ( idusuario ),
    identificacion    VARCHAR2(20) NOT NULL,
    idbibliotecario   NUMBER(4) NOT NULL
        CONSTRAINT fk_bibliotecario_prestamo
            REFERENCES bibliotecario ( idbibliotecario )
);

-- TABLA DETALLE LIBRO

CREATE TABLE detallelibro (
    iddetallelibro   NUMBER(6)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_detallelibro PRIMARY KEY ( iddetallelibro ),
    idlibro          NUMBER(6) NOT NULL,
    isbn             VARCHAR2(13) NOT NULL,
    CONSTRAINT fk_libro_detallelibro FOREIGN KEY ( idlibro,isbn )
        REFERENCES libro ( idlibro,isbn ),
    idautor          NUMBER(5) NOT NULL
        CONSTRAINT fk_autor_detallelibro
            REFERENCES autor ( idautor ),
    ideditorial      NUMBER(3) NOT NULL
        CONSTRAINT fk_editorial_detallelibro
            REFERENCES editorial ( ideditorial )
);

-- Tabla DetallePrestamo

CREATE TABLE detalleprestamo (
    iddetalleprestamo   NUMBER(6)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT pk_detalleprestamo PRIMARY KEY ( iddetalleprestamo ),
    idprestamo          NUMBER(6) NOT NULL
        CONSTRAINT fk_detalleprestamo_prestamo
            REFERENCES prestamo ( idprestamo ),
    idlibro             NUMBER(6) NOT NULL,
    isbn                VARCHAR2(13) NOT NULL,
    CONSTRAINT fk_libro_detalleprestamo FOREIGN KEY ( idlibro,isbn )
        REFERENCES libro ( idlibro,isbn )
);

INSERT INTO usuario (nombre,apellido,identificacion,sexo,nacionalidad) VALUES ('Roberto','Montano','000017547','Masculino','Nicaraguense');
INSERT INTO usuario (nombre,apellido,identificacion,sexo,nacionalidad) VALUES ('Maria','Lopez','000056489','Femenino','Ruso');
INSERT INTO usuario (nombre,apellido,identificacion,sexo,nacionalidad) VALUES ('Bryan','Perez','000023548','Masculino','Nicaraguense');
INSERT INTO usuario (nombre,apellido,identificacion,sexo,nacionalidad) VALUES ('Leonardo','Cardoza','000017562','Masculino','Estadounidense');
INSERT INTO usuario (nombre,apellido,identificacion,sexo,nacionalidad) VALUES ('Nelson','Cerros','000078523','Masculino','Aleman');

INSERT INTO UBICACION(NOMBRE)VALUES('Nicaragua');
INSERT INTO UBICACION(NOMBRE)VALUES('Mexico');
INSERT INTO UBICACION(NOMBRE)VALUES('Colombia');
INSERT INTO UBICACION(NOMBRE)VALUES('Caracas, Venezuela');
INSERT INTO UBICACION(NOMBRE)VALUES('Alemania');
INSERT INTO UBICACION(NOMBRE)VALUES('Cadiz, Espania');

INSERT INTO TIPODOCUMENTO(NOMBRE)VALUES('Libro');
INSERT INTO TIPODOCUMENTO(NOMBRE)VALUES('Tesis de Pregrado');
INSERT INTO TIPODOCUMENTO(NOMBRE)VALUES('Tesis de Posgrado');
INSERT INTO TIPODOCUMENTO(NOMBRE)VALUES('Publicaciones periodicas');
INSERT INTO TIPODOCUMENTO(NOMBRE)VALUES('Bibliografias');

INSERT INTO ESTADO(ESTADO)VALUES('EN EXISTENCIA');
INSERT INTO ESTADO(ESTADO)VALUES('EN PRESTAMO UE');
INSERT INTO ESTADO(ESTADO)VALUES('EN PRESTAMO');
INSERT INTO ESTADO(ESTADO)VALUES('BAJO CONSUMO');
INSERT INTO ESTADO(ESTADO)VALUES('AGOTADO');

INSERT INTO EDITORIAL(NOMBRE,IDUBICACION)VALUES('Monte Avila Latinoamericana, C.A.',4);

INSERT INTO AUTOR (nombre,apellido,sexo,nacionalidad) VALUES ('Antonio','Pasquali','Masculino','Venezolano');

INSERT INTO BIBLIOTECARIO (NOMBRE,APELLIDO) VALUES ('Roberto','Montano');
INSERT INTO BIBLIOTECARIO (NOMBRE,APELLIDO) VALUES ('Julian','Romero');
INSERT INTO BIBLIOTECARIO (NOMBRE,APELLIDO) VALUES ('Alberto','Reyes');
INSERT INTO BIBLIOTECARIO (NOMBRE,APELLIDO) VALUES ('Armando','Casas');
INSERT INTO BIBLIOTECARIO (NOMBRE,APELLIDO) VALUES ('Carlos','Lopez');

INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(000,'Generalidades');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(100,'Filosofía & Psicologia');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(200,'Religion')
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(300,'Ciencias Sociales');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(400,'Lenguas');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(500,'Ciencias Naturales & Matematicas');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(600,'Tecnologia (Ciencias aplicadas)');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(700,'Las Artes');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(800,'Literatura & Retórica');
INSERT INTO CATEGORIAGENERAL (CODIGOGENERAL,NOMBRE)VALUES(900,'Geografia & Historia');

INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(010,'Bibliografia',000);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(110,'Metafisica',100);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(210,'Filosofia y teoria de la religion',200);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(310,'Colecs. de estadística general',300);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(410,'Linguistica',400);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(510,'Matematicas',500);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(610,'Ciencias Medicas Medicina',600);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(710,'Urbanismo & Arte del paisaje',700);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(810,'Literatura norteameircana en ingles',800);
INSERT INTO CATEGORIAGENERAL (CODIGOESPECIAL,NOMBRE,CODIGOGENERAL)VALUES(910,'Geografia & Viajes',900);

--INSERT INTO LIBRO ()VALUES();
